### ISSUE TITLE
Defining Swipeable view dimensions within parent view

### ISSUE THREAD

**Issue by cikabole** [zhxnlai/ZLSwipeableViewSwift#1]

**Comment by zhxnlai** [comment]
Could you elaborate the question?

**Comment by cikabole** [comment]
Initially I defined my question in description. But five minutes later I figured out that positioning and size of SwipeableView have nothing with class but with Cartography layout(). 
So I tried to remove this issue, in order to avoid confusions but only description has been deleted.  
Thanks for this great component!
