### ISSUE TITLE
is possible update swift 3.1?

### ISSUE THREAD

**Issue by cookiebox33** [zhxnlai/ZLSwipeableViewSwift#100]
error: module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

**Comment by AndrewSB** [comment]
Yup! I'll take care of this in the next couple weeks, but i can review a PR that upgrades this much sooner 😊

**Comment by 0zguner** [comment]
@AndrewSB any progress on this issue ?

**Comment by coolcool1994** [comment]
Did developers here send an update to cocoa pod for Swift 3.1?

**Comment by jmanoel** [comment]
Did developers here send an update to cocoa pod for Swift 3.1?

**Comment by coolcool1994** [comment]
No, I ended up using objective-c version which works just as well. This developer didn't update the cocoa pod

**Comment by jmanoel** [comment]
Thanks. I will do the same. Best regards
