### ISSUE TITLE
No such file in cocoaPods

### ISSUE THREAD

**Issue by cookiebox33** [zhxnlai/ZLSwipeableViewSwift#102]
hi, when i pull by cocoaPods, system waring me "no such module ZLSwipeableViewSwift"
how to fix this?

**Comment by AndrewSB** [comment]
can you share your Podfile so we can help debug this with you?

**Comment by cookiebox33** [comment]
hi @AndrewSB:
I am fixed this, i did clone wrong branch :( 
thank you for your help~
