### ISSUE TITLE
Issue with tableview inside card view

### ISSUE THREAD

**Issue by kamlesh-jswal** [zhxnlai/ZLSwipeableViewSwift#105]
Hello All,

if i am using table view inside CardContentView xib and reloading in Cardview.swift file ....in card always showing last data for each card.
Please help me.

Thanks in Advance.

**Comment by AndrewSB** [comment]
can you share some the relevant bits of the code you're having issues with?

**Comment by FeminaBrahmbhatt** [comment]
I am not able to scroll tableview in card view

**Comment by FeminaBrahmbhatt** [comment]
How did you solved that?

Thanks,
Femina Brahmbhatt
feminabrahmbhatt6@gmail.com

**Comment by kamlesh-jswal** [comment]
I was having an issue related to data display, that I was passing wrong. when I debug closely I found the issue, it was my mistake.

table scroll is working fine for me. I just added a table in xib.
