### ISSUE TITLE
Card rotation during swiping

### ISSUE THREAD

**Issue by noordawod** [zhxnlai/ZLSwipeableViewSwift#106]
Hi again.

Is it possible to control the amount of rotation applied to the card while swiping regardless of where the finger touches the card? There doesn't seem to be a parameter for that, and I can't find the snippet of code where this is controlled (my first bet is ViewManager).

If you could me a bit here, I can send a pull request to add this functionality.

Thanks.

**Comment by AndrewSB** [comment]
there's an abandoned pull request that implemented this (#76) that should work for you. I'm still happy to merge it in once it's finished up 😄

**Comment by noordawod** [comment]
Hey @AndrewSB, thanks for the answer :)
That pull request is... a little misguided. I'll try to take the best out of it and send a pull request later today.
