### ISSUE TITLE
Help Setting Up

### ISSUE THREAD

**Issue by alexgoodison** [zhxnlai/ZLSwipeableViewSwift#108]
Hi,

I just came across ZLSwipeableView and I am excited to use it but a bit confused as to how to use it. I thought that I had everything setup correctly but I can't swipe the `testView` Here is my code: 

```
var testView = UIView()
    @IBOutlet weak var swipeableView: ZLSwipeableView!
  
    override func viewDidLoad() {
        super.viewDidLoad()
        
        testView.frame.size = CGSize(width: 300, height: 500)
        testView.backgroundColor = UIColor.black
        testView.layer.cornerRadius = 16
        testView.clipsToBounds = true

        swipeableView.allowedDirection = Direction.All
        swipeableView.numberOfActiveView = 3
        swipeableView.nextView = {
            return self.testView
        }
        swipeableView.loadViews()
        
        view.addSubview(swipeableView)
        
    }
```

Any help appreciated.

**Comment by AndrewSB** [comment]
I see that you're using an `IBOutlet`, and then you're also adding the `swipeableView` as a subview. It looks as if there might just be some non-ZLSwipeableView specific issues with your code. 

Have you decided between using the storyboard/nib or code? If so, have you setup auto layout?

**Comment by alexgoodison** [comment]
@AndrewSB  I switched to using an `IBOutlet` although I had the same issues if the `ZLSwipeableView` was created programmatically. I am using the Storyboard and I have constraints setup on the `swipeableView`. Basically, I get the same issue if I create if with storyboard or set it up using Swift.

**Comment by AndrewSB** [comment]
can you see the swipeableView? for eg. change it's background color to green and tell me if you see a green square in your view?

**Comment by alexgoodison** [comment]
<img width="1110" alt="screen shot 2017-08-30 at 21 39 17" src="https://user-images.githubusercontent.com/17804268/29893962-c11be67c-8dcb-11e7-8628-fc7b7956c139.png">

@AndrewSB  This is the result. The black view is the `testView` which is supposed to be the view that you can swipe
