### ISSUE TITLE
Pod is not installing the swift 4 version 

### ISSUE THREAD

**Issue by zubairghori** [zhxnlai/ZLSwipeableViewSwift#111]
<img width="566" alt="screen shot 2017-09-27 at 5 37 09 pm" src="https://user-images.githubusercontent.com/8655968/30913742-a943daf6-a3aa-11e7-8e04-2b76147d9bdb.png">
its installing the  pod 'ZLSwipeableViewSwift'   0.0.7 by default

**Comment by alvincrisuy** [comment]
Same here

**Comment by AndrewSB** [comment]
hey! we haven't cut a release for swift 4 yet, for now, you can edit your Podfile to specify the commit that adds swift 4 support

```
pod 'ZLSwipeableViewSwift', :git => 'https://github.com/zhxnlai/ZLSwipeableViewSwift.git', :commit => '59826e2'
```
