### ISSUE TITLE
Limit rotation angle for UIAttachmentBehavior

### ISSUE THREAD

**Issue by denirorobert** [zhxnlai/ZLSwipeableViewSwift#115]
Hi, I want to allow card rotation up to 10 degrees. Now when I drag a card can be rotated for 360 degrees. I want to restrict rotation by 10 degrees for all directions.

I found that you use this line to describe attachment behavior:
`UIAttachmentBehavior(item: view, offsetFromCenter: UIOffset(horizontal: -(p.x - point.x), vertical: -(p.y - point.y)), attachedTo: anchorView, offsetFromCenter: UIOffset.zero)`

I've check UIAttachmentBehavior API and unfortunately there is only one method that restricts rotation:

> A sliding attachment allows for relative translation of two items along a specified axis with respect to the anchor point. A sliding attachment prevents all relative rotation of the dynamic items.

`open class func slidingAttachment(with item1: UIDynamicItem, attachedTo item2: UIDynamicItem, attachmentAnchor point: CGPoint, axisOfTranslation axis: CGVector) -> Self
`

Unfortunately this method makes dragging linear and also doesn't allow to rotate the card up to 10 degrees.
May be you know the easies way how to implement this in your framework?

You can check how Tinder cards rotation is implemented now to better understand what I am trying to achieve.

**Comment by denirorobert** [comment]
solution was found

**Comment by souvik22** [comment]
How did you solve that issue? Can you please share.
