### ISSUE TITLE
Top card not interactive after rewinding

### ISSUE THREAD

**Issue by tungvoduc** [zhxnlai/ZLSwipeableViewSwift#116]
After rewinding, I am not able to interact with the top card(previous card) at all. When dragging, only the cards below it is being moved.

**Comment by ethan021021** [comment]
Any update on this issue? I'm getting the same issue.

**Comment by AndrewSB** [comment]
Thanks for opening an issue to track this 👍 I'd be more than happy to accept a PR that fixes the behavior
