### ISSUE TITLE
Invalid card positioning

### ISSUE THREAD

**Issue by ghost** [zhxnlai/ZLSwipeableViewSwift#120]
Steps to reproduce:
1. Launch demo.
2. Select "Default".
3. Drag a card around a bit http://take.ms/fhPQH.
4. Rotate device or simulator.

Issue:
Card is misplaced http://take.ms/7wHWW.

**Comment by AndrewSB** [comment]
😬 doesn't seem great.
Can you try calling layoutSubviews after the device rotates to see if that fixes the issue? We'd be very open to accepting a PR that fixes the behavior.

Thanks for the report 😄

**Comment by algrid** [comment]
Hi, I had the same problem.

Added a pull request with the fix: https://github.com/zhxnlai/ZLSwipeableViewSwift/pull/129
