### ISSUE TITLE
why can not  find compatible versions for pod "ZLSwipeableViewSwift":   In Podfile:     ZLSwipeableViewSwift (~> 0.0.8)

### ISSUE THREAD

**Issue by XychloveFhy** [zhxnlai/ZLSwipeableViewSwift#123]
Hello 
I pod your project with 0.0.7 ,and some many warning in my project, so I pod 0.0.8, 

[!] CocoaPods could not find compatible versions for pod "ZLSwipeableViewSwift":
  In Podfile:
    ZLSwipeableViewSwift (~> 0.0.8)

None of your spec sources contain a spec satisfying the dependency: `ZLSwipeableViewSwift (~> 0.0.8)`.
the I use the pod 'ZLSwipeableViewSwift', :git => 'https://github.com/zhxnlai/ZLSwipeableViewSwift.git'
it‘s also not success,
Can you help me?

**Comment by AndrewSB** [comment]
@XychloveFhy try this https://github.com/zhxnlai/ZLSwipeableViewSwift/issues/111#issuecomment-337086465, and let me know if that works for you
