### ISSUE TITLE
Update to Swift 4

### ISSUE THREAD

**Issue by ivancantarino** [zhxnlai/ZLSwipeableViewSwift#126]
Hello everyone.

I'm just wondering if there is any plans to update the framework to Swift 4? I have noticed that there are a lot of code collisions.

**Comment by AndrewSB** [comment]
@Ivan-Cantarino: `master` supports swift 4, as of #110.

**Comment by ivancantarino** [comment]
Oh... somehow I just used the latest pod and got a lot of code collisions, thus my comment. 
I’ll try the latest master branch.
Thank you

**Comment by sunny131984** [comment]
is there any plan for pod release.
