### ISSUE TITLE
How can set the imageView width?

### ISSUE THREAD

**Issue by whitefox0102** [zhxnlai/ZLSwipeableViewSwift#127]
I set the imageView in the func [setup]

and I set the photo and set the contentMode to "UIViewContentModeScaleAspectFill"

But the width of the photo will exceed the screen

how should I do to limit the size

thanks!

**Comment by AndrewSB** [comment]
It's hard to say without seeing more of your implementation. I'd say that this is a classic UIKit issue you're running into, not specific to using this library.
I'd recommend trying to add your `imageView` to a simple view, and then check to see if it looks right, once it does, then try adding it back to the `swipeableView`.

**Comment by whitefox0102** [comment]
I fixed it 
set uiimageview's masksToBounds = true
thanks!
