### ISSUE TITLE
Bottom Animation while loading card first time

### ISSUE THREAD

**Issue by mBilal5674** [zhxnlai/ZLSwipeableViewSwift#130]
How to stop animation from bottom when reload card

**Comment by AndrewSB** [comment]
You should be able to do a `swipeableView.layoutIfNeeded()`, and that should make it so the card goes to the initial position with no animation.

**Comment by mBilal5674** [comment]
Thanks AndrewSB. You save my day. Can you tell me how to load card at specific index without reload card.

**Comment by AndrewSB** [comment]
That's very specific to your implementation, so without understanding how you're using the library it would be hard to say.
If you're only interested in showing a card with no animation, you could 

```swift
// set the current index correctly
swipeableView.loadViews()
swipeableView.layoutIfNeeded()
```

which should change the replace the card with no animation.

**Comment by mBilal5674** [comment]
Can,t Jump to specific card.
