### ISSUE TITLE
Can't Change NumberofActiveView 

### ISSUE THREAD

**Issue by mBilal5674** [zhxnlai/ZLSwipeableViewSwift#131]
I can't change number of active view from default value to other.

**Comment by AndrewSB** [comment]
I can't help you fix your issue unless you share your code. Ideally, the best way I can help you debug this is by you creating a Pull Request with a new demo which would illustrate changing the number of active views, and we can work together to make that demo work

**Comment by mBilal5674** [comment]
ok fine. I have almost fix my issue and just i found one issue in my code i
can't get current card index. After i fix this issue i create a pull
request so that other user enjoy it.

**Comment by AndrewSB** [comment]
awesome! Thank you for sharing your learnings with the community by opening that PR 😄
