### ISSUE TITLE
update pod to 0.0.8

### ISSUE THREAD

**Issue by junjielu** [zhxnlai/ZLSwipeableViewSwift#132]
Hi, thanks for your great job! I notice that the latest version of ZLSwipeableViewSwift is ``0.0.8``.However, the version in specs repo is ``0.0.7``. Would you mind push your spec to specs repo so everybody can use this framework in swift 4 and later?

**Comment by AndrewSB** [comment]
@junjielu could you link me to a guide on how to do that please? I've always used Carthage

**Comment by junjielu** [comment]
> @junjielu could you link me to a guide on how to do that please? I've always used Carthage

You can check this official guide: https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by t0milee** [comment]
I see that the podspec is updated in the repo, so I think it just needs to be updated on cocoapods, does anyone know when this will be done?

**Comment by AndrewSB** [comment]
closed by #144
