### ISSUE TITLE
Swift compile error

### ISSUE THREAD

**Issue by richardpap** [zhxnlai/ZLSwipeableViewSwift#133]
Hey,

I installed the library tru cocoapods, and when i try to build the app, i get swift compile errors.
(XCode 10, Swift 4.2, CocoaPods 1.5.3). Anyone else have the same issue?

Best,
Richard

**Comment by junjielu** [comment]
Same issue #132 .You can put `pod 'ZLSwipeableViewSwift', :git => 'https://github.com/zhxnlai/ZLSwipeableViewSwift.git', :branch => 'master'` in your Podfile as a workaround

**Comment by AndrewSB** [comment]
Yeah, this would be fixed by #132, that workaround should work for now. Instead of `master` you could also just put in the current commit hash 18d6109a7be65bb76eb57dd63bbe9d2e43b4ebfc
