### ISSUE TITLE
Automatic Swipe in random directions?

### ISSUE THREAD

**Issue by chgaurav92** [zhxnlai/ZLSwipeableViewSwift#140]
Is there a way we can swipe the cards in random directions for few seconds or a given time and then stop the animation? I am trying to achieve automatic swipe animation of cards in random directions on single button click and it should animate for few seconds and then stop it. Any help would be appreciated. Thanks!

**Comment by AndrewSB** [comment]
you could write an implementation that generates random numbers from 1-2pi, then instructs the swipeable view to swipe a card in that direction. once you no longer want to have the cards swipe, you can stop generating the numbers
