### ISSUE TITLE
Cocoapod installation not working

### ISSUE THREAD

**Issue by Punitbansal** [zhxnlai/ZLSwipeableViewSwift#142]
Not able to install version higher than 0.0.7 via cocoa pods as the version is not present in pod spec repo. Please check the screenshot
<img width="1791" alt="Screenshot 2019-10-17 at 11 25 05 AM" src="https://user-images.githubusercontent.com/8542747/66981319-fd986e80-f0d0-11e9-8f00-01b256cbba2f.png">

**Comment by AndrewSB** [comment]
I’m sorry, I haven’t been maintaining the cocoapod just because i’m not used to using it :/

specify a git tag in your Podfile? Then you can use a release from github?

**Comment by AndrewSB** [comment]
closed by #144
