### ISSUE TITLE
Leak memory

### ISSUE THREAD

**Issue by lexuanquynh** [zhxnlai/ZLSwipeableViewSwift#146]
I got leak memory when use function in demo:
swipeableView.nextView = {
            return self.nextCardView()
        }
I think we need capture to free swipeableView when parent view controller deinit:

swipeableView.nextView = { [weak self] in
            return self?.nextCardView()
        }

**Comment by AndrewSB** [comment]
yup, that looks right @lexuanquynh. in your first example your strongly capturing `self`, which is a strong reference cycle. `[weak self]` will prevent that cycle
