### ISSUE TITLE
SwiftUI

### ISSUE THREAD

**Issue by riley-usagi** [zhxnlai/ZLSwipeableViewSwift#147]
This project looks amazing! But there is 2021 =)

Do you plan to create a new version for SwiftUI?

**Comment by AndrewSB** [comment]
no plans to reimplement in SwiftUI, but its totally usable in SwiftUI by wrapping inside a `UIViewRepresentable`.

If you end up implementing a good `UIViewRepresentable` wrapper, send us a pull request 😄

**Comment by riley-usagi** [comment]
Good idea, Thanks!

**Comment by alldritt** [comment]
I know I'm late to this thread, but here is a prototype SwiftUI wrapper for ZLSwipableViewSwift.  It's not fully complete but shows how to get started.

https://github.com/alldritt/ZLSwipeableViewSwiftUI

There is quite a bit to think about when mapping ZLSwipableViewSwift into SwiftUI.  The issue of how and when card views are created needs to be considered carefully given the declarative nature of SwiftUI.

**EDIT**: version 0.2.0 introduces a fully declarative interface.
