### ISSUE TITLE
Build from swift-2 branch fails

### ISSUE THREAD

**Issue by orkenstein** [zhxnlai/ZLSwipeableViewSwift#15]
Fails with error:
![2015-08-25 17-01-39 zlswipeableview swift](https://cloud.githubusercontent.com/assets/1461936/9468571/fe789616-4b4a-11e5-9578-ed5fae5431ab.png)

**Comment by orkhanalizade** [comment]
@orkenstein Look at my repository based on this: <a href="https://github.com/orkhanalizade/Tinderable"> Tinderable</a>

It written in Swift2

**Comment by zhxnlai** [comment]
Done. The swift 2 branch has been updated and merged.
