### ISSUE TITLE
Labels inside the view don't move synchronously with a card view. 

### ISSUE THREAD

**Issue by kondranton** [zhxnlai/ZLSwipeableViewSwift#19]
Labels inside the card view don't move synchronously with a card view. I implement constraints programmatically. Besides that, when I move the card, it gets bigger together with label.

**Comment by zhxnlai** [comment]
Please take a look at this file: https://github.com/zhxnlai/ZLSwipeableView/blob/master/ZLSwipeableViewDemo/ZLSwipeableViewDemo/ZLSwipeableViewController.m
