### ISSUE TITLE
Integrate this in Obj c

### ISSUE THREAD

**Issue by juneadahd** [zhxnlai/ZLSwipeableViewSwift#2]
I want to integrate this class in obj c how to use it.

**Comment by timbroder** [comment]
@juneadahd have you seen the objc version? https://github.com/zhxnlai/ZLSwipeableView

**Comment by akac** [comment]
Just my two cents. We have a major iOS project written in objective c. However all new code is Swift only. So projects like this are interesting. 

If I wanted to use this project, for example, I would make it usable from obj c. One way to do that would be to extend current obj c classes in swift - which can use this project.

**Comment by skram** [comment]
New to swift, How would you implement this Swift version in an Objective-C project? Seems ObjC version is no longer maintained. Thanks @broderboy @akac @zhxnlai

**Comment by AndrewSB** [comment]
@skram https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID122
