### ISSUE TITLE
Undo doesn't work as expected

### ISSUE THREAD

**Issue by sumitlni** [zhxnlai/ZLSwipeableViewSwift#21]
When using the `UndoDemoViewController` from example, the layer on top changes before `insertTopView` is called. So for example, if we have green, blue and red as the cards, and we swipe green, followed by hitting "undo", the top card changes to red. You can easily recreate this issue by reducing the number of cards to 3 so you can see the distinct colors.

**Comment by zhxnlai** [comment]
`UndoDemoViewController` has been replaced by `HistoryDemoViewController`. Could you try out the latest demo project and see if the issue still exists?

**Comment by sumitlni** [comment]
Works beautifully, and is a much more usable implementation! Thanks so much!
