### ISSUE TITLE
I'd like to change the way how cards are stacked, how could I do it?

### ISSUE THREAD

**Issue by zzdjk6** [zhxnlai/ZLSwipeableViewSwift#22]
I'd like to use this lib instead of Koloda View to get advantage of REWIND feature.
But can anyone help me with the way how cards are stacked?
I'd like to make it just like Koloda View does.

![example](https://github.com/Yalantis/Koloda/raw/master/Koloda_v1_example_animation.gif)

**Comment by zzdjk6** [comment]
@zhxnlai

**Comment by zzdjk6** [comment]
well, I found that assign custom handler for "swipeView.animateView" can solve this.

**Comment by AndrewSB** [comment]
awesome! Glad you were able to figure it out @zzdjk6
