### ISSUE TITLE
如何获取当前卡片里的数值

### ISSUE THREAD

**Issue by DiamondYuan** [zhxnlai/ZLSwipeableViewSwift#24]
我在nextCardView()里add了一个label,那么在swipeableView.didSwipe里面如何获得当前卡片的label的值。
我创建了一个全局变量，但是只能获得当前卡片后第四张卡片的label的Text

**Comment by AndrewSB** [comment]
@GeorgeYuen I don't completely understand what you're trying to do, something about accessing the currentCardView in a delegate method?

Closing this for now, if you re-explain I can try to help you out
