### ISSUE TITLE
swiping distorts imageview (which is a subview of swipeable view)

### ISSUE THREAD

**Issue by stanchiang** [zhxnlai/ZLSwipeableViewSwift#25]
in my card view.swift file i'm adding an image view to fit the bounds of the swipeable view. this looks normal at first. however when i start dragging the swipeable view, the image becomes much larger. 

this is more of an issue with how I'm using the cartography pod, but since you guys used it in the original library. I thought you guys could help me diagnose the issue.

i tried using the following thinking that it was gonna be very straightforward, but i don't know what to do anymore. The constraints don't seem to respect the card bounds when it starts being translated and rotated.

Any advise please?

```
    constrain(imageView, self) { obj1, obj2 in
        obj1.width == obj2.width
        obj1.height == obj2.height
        obj1.left == obj2.left
        obj1.right == obj2.right
        obj1.bottom == obj2.bottom
        obj1.top == obj2.top
    }
```

**Comment by stanchiang** [comment]
![before](https://cloud.githubusercontent.com/assets/3621407/11777661/a8ed7dc2-a204-11e5-9a30-ff32b2ded58d.png)

![after](https://cloud.githubusercontent.com/assets/3621407/11777660/a8ce9efc-a204-11e5-948f-8e6c52b6a944.png)

**Comment by mamalat** [comment]
Why won't just use imageView.frame = view.frame. 
Does your app support orientations? If not, than you are good with that.

**Comment by stanchiang** [comment]
hmm...i tried, but as soon as i start dragging the card, the image stops adhereing to the original size and the image starts scaling in proportion to the translation of the card. 

where would you suggest i put that line?

here is a link to the repo
https://github.com/stanchiang/WatchProject

**Comment by stanchiang** [comment]
thanks, no constraint needed

**Comment by mamalat** [comment]
I was just about to type that.

**Comment by stanchiang** [comment]
oh cool :) but i'm curious (still an ios noob) why does setting the frame work but not the constraint in this case?

**Comment by rainymoodone** [comment]
Can also be like this, from left and top
         imageView.snp.makeConstraints { (m) in
            m.edges.equalTo(self)
            m.left.top.equalTo(self)
            m.width.equalTo(100)
            m.height.equalTo(200)
         }
