### ISSUE TITLE
Init with frame initialiser is not visible for some reason

### ISSUE THREAD

**Issue by jonauz** [zhxnlai/ZLSwipeableViewSwift#27]
I setup using cocoapods and did `import ZLSwipeableViewSwift` and when I tried to use it exactly as in an setup instructions, I noticed that `init(frame: CGRect)` is not visible. It throws me an error.

`ZLSwipeableView(frame: CGRectMake(0, 0, 300, 500))`
`Incorrect argument label in call (have 'frame:', expected 'coder:')`

I can see that class has 

```
 override init(frame: CGRect) {
    super.init(frame: frame)
    setup()
}
```

but not sure why it doesn't see it.

Sample shows `swipeableView = ZLSwipeableView()`, but GitHub setup shows 
"`var swipeableView = ZLSwipeableView(frame: CGRect(x: 0, y: 0, width: 300, height: 500)))`"

`swipeableView.numPrefetchedViews = 3` is deprecated, but is shown in how to setup this library here in Readme.

**Comment by efremidze** [comment]
Since `override init(frame: CGRect)` is not public, you can't override it. I'm having the same issue.

**Comment by AndrewSB** [comment]
@jonauz I've added a public modifier to the initWithFrame function in https://github.com/zhxnlai/ZLSwipeableViewSwift/commit/c70fc79a6660e51efa775e1896eccbe73c0d609e
