### ISSUE TITLE
How to make swipes always look programmatic?

### ISSUE THREAD

**Issue by kajensen** [zhxnlai/ZLSwipeableViewSwift#29]
Basically, I want to disable the anchoring to the touch point and also disable vertical movement (I already have the allowed directions set to horizontal) so that the swipes always look like the programmatic calls. I only have an interest in left & right swipes. How would one go about this? I'm fine if you point me in the general direction for where to go about this as i'm sure it will require some customization on my end. Thanks.

**Comment by AndrewSB** [comment]
Why not disable user interaction and a pan gesture recognizer, which would
make programmatic swipe calls?

**Comment by kajensen** [comment]
Considered that, but I think I want the option to also "grab" the view and drag it around, and also cancel the swipe. The programmatic swipes seem to be an all or nothing thing. I guess I could customize it so its not but that seems like a similar amount of work the other way. Basically I want to standardize the "path" of the swipe animation

**Comment by AndrewSB** [comment]
You could potentially grab the x offset from the pan recognizer and pass it
directly to the ZLSwipeableView with a normalized y value?

**Comment by kajensen** [comment]
i'll give it a go, thanks!

**Comment by AndrewSB** [comment]
😀 let me know if it works!

**Comment by kajensen** [comment]
I couldn't get it to work exactly as I wanted. I'm now working on just disabling the anchoring/rotation of the view on gesture

**Comment by AndrewSB** [comment]
💯

**Comment by AndrewSB** [comment]
closing this due to staleness
