### ISSUE TITLE
Give the library a swiftier name

### ISSUE THREAD

**Issue by AndrewSB** [zhxnlai/ZLSwipeableViewSwift#30]
Maybe a name that isn't namespaced? Namespacing is outdated now.

Would you be onboard @zhxnlai?

**Comment by zhxnlai** [comment]
Totally! What do you have in mind?

**Comment by remaerd** [comment]
Simply 'Swipable' or 'Stacks' or 'Card' would be fine.

**Comment by AndrewSB** [comment]
@zhxnlai I like `Stack` or `CardStack`, what do you think?

**Comment by AndrewSB** [comment]
Or `Cards`

**Comment by AndrewSB** [comment]
@zhxnlai @remaerd: what do you two think of going ahead with Cards? If there are no objections, I can go ahead and migrate later this next week?
