### ISSUE TITLE
No indexes?

### ISSUE THREAD

**Issue by beamercola** [zhxnlai/ZLSwipeableViewSwift#34]
Maybe I'm thinking about this the wrong way, but without indexes I'm having a hard time figuring out how to hook up a proper datasource.

Seems like I need to keep a manual count in nextView and constantly check if it's the last one to roll it back to zero?

Would be really nice to have `.nextView { (index) in` - but perhaps I'm not thinking about it the right way

Thanks!

**Comment by AndrewSB** [comment]
The API was designed similar to UIKit. Just like how UIPageViewController doesn't give you indices (only a number of pages, nextPage, and previousPage), as does `ZLSwipeableView` only let you control the visible cards through `numberOfActiveViews`, `nextView`, and `previousView`.

So yes, the easiest thing would be to add a manual count to `nextView`
