### ISSUE TITLE
Adding a tap gesture

### ISSUE THREAD

**Issue by nahouto** [zhxnlai/ZLSwipeableViewSwift#36]
Hi,
I am trying to add a tap gesture recognizer to the swipeableView. How can I do that properly ?
Thanks !

**Comment by zhxnlai** [comment]
Please take a look at [this pull request](https://github.com/zhxnlai/ZLSwipeableViewSwift/pull/35)

**Comment by nahouto** [comment]
It works wonderfully well ! Thanks a lot !
