### ISSUE TITLE
Exclude files in Pods directory

### ISSUE THREAD

**Issue by remaerd** [zhxnlai/ZLSwipeableViewSwift#39]
Hello Zhixuan, Thanks for your contribution.

I'm using Carthage with ZLSwipeableViewSwift and it's impossible to download the entire framework. The GFW is making everything slow as hell and I'm spending most of my time to download GIFs and Pods I don't want. Can you .gitignore them with a new commit? It'll optimize the entire download process who have weak internet connection like me.

Thank you again.

**Comment by AndrewSB** [comment]
@remaerd your issue sounds totally valid. I'm not that familiar with Cocoapods (more of a Carthage guy), but if you submit a PR I'd be happy to merge it in!

**Comment by AndrewSB** [comment]
Just noticed you said you needed help optimizing Carthage, not cocoa pods, my mistake!

**Comment by AndrewSB** [comment]
closing due to staleness
