### ISSUE TITLE
Unable to build demo project: "No such module ReactiveUI

### ISSUE THREAD

**Issue by fwielstra** [zhxnlai/ZLSwipeableViewSwift#4]
I naively cloned the project; both before and after running 'pod install' I get this build error.

Cocoapods 0.37.2, xcode 6.3.2

**Comment by thefaj** [comment]
The dependency on Reactive is 💩

**Comment by Jsonmess** [comment]
I get this build error too,but when I change build target to 'ios8.3~',the error disappear.

more,pod can't load this repository ,maybe cocoapods config file have some error in ios7

**Comment by AndrewSB** [comment]
Is this still an issue for you guys?
