### ISSUE TITLE
Can't get Custom Direction to work. Help?

### ISSUE THREAD

**Issue by felipecaldas** [zhxnlai/ZLSwipeableViewSwift#40]
Hi there,

I want the cards to only be swippable left and right. I tried this:

swipeableView.allowedDirection = .Left | .Right but I am getting the following error in XCode 7.2.1:

ZLSwipeableViewController.swift:111:62: Binary operator '|' cannot be applied to two 'Direction' operands

What am I doing wrong?

Thanks

**Comment by felipecaldas** [comment]
By the way, I also tried:
        self.swipeableView.allowedDirection = Direction.Horizontal

It is accepting Up and Down swipes.

**Comment by felipecaldas** [comment]
Hi everyone. Still struggling to get this working. Now on XCode 7.3 with the very latest version of the library I get:

 No '|' candidates produce the expected contextual result type 'Direction'

This is from: self.swipeableView.allowedDirection = Direction.Left | Direction.Right

Can please anyone help.

**Comment by AndrewSB** [comment]
Hey @Solum, 

Have you tried `swipeableView.allowedDirection = [.Left, .Right]`?

**Comment by felipecaldas** [comment]
Hi Andrew! 

Thank you very much for the help. The suggested does work, in the sense that it does not throw any error. But, I can still swipe up or down, which I don't want.

So, this is what I have in my ViewController:

> self.swipeableView.allowedDirection = [Direction.Left , Direction.Right]

And, this is what the ZLSwipeableView class has:

> public var allowedDirection = Direction.Horizontal

The funny thing is that if I set the Left and Right in the ZLSwipeableView itself, like this:

> public var allowedDirection = [Direction.Left, Direction.Right]

Then I see these errors:

```
func isDirectionAllowed() -> Bool {
                return Direction.fromPoint(translation).intersect(allowedDirection) != .None
            }
ZLSwipeableView.swift:387:67: Cannot convert value of type '[Direction]' to expected argument type 'Direction'
```

and

> @available(*, deprecated=1, message="Use allowedDirection")
>     public var direction: Direction {
>         get {
>             return allowedDirection
>         }
>         set(newValue){
>             allowedDirection = newValue
>         }
>     }
> ZLSwipeableView.swift:420:20: Cannot convert return expression of type '[Direction]' to return type 'Direction'
> ZLSwipeableView.swift:423:32: Cannot assign value of type 'Direction' to type '[Direction]'

Any help much appreciated ;)

**Comment by AndrewSB** [comment]
@Solum can you give more details on your usage? In this [example](https://github.com/zhxnlai/ZLSwipeableViewSwift/blob/master/ZLSwipeableViewSwiftDemo/ZLSwipeableViewSwiftDemo/CustomDirectionDemoViewController.swift#L23) `swipeableView.allowedDirection = .Horizontal` works.

Are you sure you aren't overriding the `allowedDirection` later?

**Comment by felipecaldas** [comment]
Hi @AndrewSB  thanks again for the support.
Indeed, I have seen the example. Since I just want my cards to work Left or Right, simply setting `allowedDirection` to Horizontal would suffice, wouldn't it?

Which one is the function that gets called when one swipes and will check if it's allowed or not? I tried to put a break point at `defaultShouldSwipeViewHandler` but it did not get called.

**Comment by felipecaldas** [comment]
Alright, I found what the problem was. I had this in my VC:

`swipeableView.shouldSwipeView = { _, _, _ in true }`

It was then rewriting the delegate and thus not checking the `allowedDirection`. Sorry Andrew for the trouble!!

Thanks,

**Comment by AndrewSB** [comment]
Glad you were able to get this to work!
