### ISSUE TITLE
Update subview after layout

### ISSUE THREAD

**Issue by nahouto** [zhxnlai/ZLSwipeableViewSwift#43]
Hi,

I use this wonderful library to display cards which contained many informations.
In a card, there is a circle shape view ( `cornerRadius = height /2` )
 but it appears diamond shape.

To avoid that strange effect, I used to set that in a UIViewController : 
    override func viewDidLayoutSubviews() {
myView.layer.cornerRadius = myView.frame.size.width /2
}

How to do that in SwipeableView ?

I tried to set in nextCardView() : 

```
    for i in 0..<swipeableView.activeViews().count {
        if let cardView = swipeableView.activeViews()[i] as? CardView {
            cardView.myView.layer.cornerRadius  = cardView.myView.frame.size.width / 2
        }
    }
```

it works but not in the last active view.

Thank you very much !

**Comment by AndrewSB** [comment]
@nahouto are you still experiencing this? If so, sharing an example project would be extremely helpful to debug with

**Comment by AndrewSB** [comment]
closing due to staleness

**Comment by nahouto** [comment]
This problem is still there, I have to make a demo project...
