### ISSUE TITLE
iPad slow animation

### ISSUE THREAD

**Issue by wieweb** [zhxnlai/ZLSwipeableViewSwift#46]
If your call `swipeTopView(inDirection direction: Direction)` the animation on iPad is very slow. Sometimes the duration is up to 5 seconds, depending on iPad model.

We are using swift 2.2 with iOS9

**Comment by AndrewSB** [comment]
@wieweb are you testing this on a device or the simulator?

**Comment by AndrewSB** [comment]
Closing due to staleness - let me know if there's anything we can do @wieweb
