### ISSUE TITLE
modify the animation

### ISSUE THREAD

**Issue by HunterMz** [zhxnlai/ZLSwipeableViewSwift#50]
hi, I would like to ask you how to modify the rebound amplitude of cardView  when it back to the primary position?

**Comment by AndrewSB** [comment]
@HunterMz [here's](https://github.com/zhxnlai/ZLSwipeableViewSwift/blob/master/ZLSwipeableViewSwift/ZLSwipeableView.swift#L250) the default implementation for the animation. There hasn't yet been an easily integratabtle implementation of custom animations.

I'd be happy to merge in a PR that provides that functionality, I think it would be a nice addition to the library too 😄

**Comment by AndrewSB** [comment]
Closing due to staleness - happy to merge in a modifiable animation if you make one!
