### ISSUE TITLE
didTap not availambe from cocopoads

### ISSUE THREAD

**Issue by sgandro** [zhxnlai/ZLSwipeableViewSwift#51]
didTap not availambe from cocopoads.

**Comment by AndrewSB** [comment]
@sgandro I just updated the podspec, you should now be able to use `didTap`

**Comment by sgandro** [comment]
Thanks, but when I executed pod install or pod update, it download 0.0.5 version... this is the last.

**Comment by sgandro** [comment]
I'm see that you was updated https://www.cocoacontrols.com/controls/zlswipeableviewswift 7 days ago, but when I updated pod, I was 0.0.5 version

Thanks!!!!

**Comment by AndrewSB** [comment]
@sgandro I'm not very familiar with cocoapods, I made [this](https://github.com/zhxnlai/ZLSwipeableViewSwift/commit/24116110d40105874fc7dfe954cd73594c8b8acc) commit, which I thought would point cocoapods to 0.0.7. Do you know why that isn't the case?

**Comment by sgandro** [comment]
I solve in this mode
inside PodFile
pod 'ZLSwipeableViewSwift', :git => 'https://github.com/zhxnlai/ZLSwipeableViewSwift.git'

Now!... I can try to implement next and previous, swipe left -> next, swipe right -> previous... can you help me to implement this mode? Thanks

**Comment by zhxnlai** [comment]
I just updated the pod to the 0.0.7 release, and the problem has been resolved. Check out https://cocoapods.org/pods/ZLSwipeableViewSwift

**Comment by AndrewSB** [comment]
Thanks @zhxnlai
