### ISSUE TITLE
How to return number of views like UITableview data source?

### ISSUE THREAD

**Issue by karthisiva** [zhxnlai/ZLSwipeableViewSwift#58]
I am trying your sample, i cannot set number of views, i want to set only five view, which property i need to use before view is loading.
                 self.swipeableView.numberOfActiveView = 5;
                self.swipeableView.discardViews()
                self.swipeableView.loadViews()

i dont understand here

**Comment by AndrewSB** [comment]
Make sure you're setting the `numberOfActiveViews` before the initial
`loadViews()` (there's a possibility that `loadViews()` is called
internally in the library, and then also remove your call to
`discardViews()`, as that will discard the first x views already loaded by
the initial `loadViews()`

**Comment by AndrewSB** [comment]
closing due to staleness
