### ISSUE TITLE
Can't form Range with end < start

### ISSUE THREAD

**Issue by sgandro** [zhxnlai/ZLSwipeableViewSwift#59]
Hi,
when I try to make rewind... I receive range error in loadViews()
Why in your example project not yet ? 
I'm use Storyboard
thanks

**Comment by AndrewSB** [comment]
@sgandro this was discussed in #49, and #53 should have fixed it. Have you checked out a version of the code that includes that commit?

**Comment by sgandro** [comment]
0.0.7 but probably by cocopods I've problems!

Thanks

**Comment by ejmartin504** [comment]
Pulling from master does fix this for me. Please release! 💃

**Comment by jboulter11** [comment]
The current fix for this is bugged.  See #64 for new fix and explanation.

**Comment by AndrewSB** [comment]
merged #64 🎉
