### ISSUE TITLE
Trying to load actual data into cards using xib file. 

### ISSUE THREAD

**Issue by laurennicoleroth** [zhxnlai/ZLSwipeableViewSwift#6]
Am unable to use outlets in CardView.swift to set any data in CardContentView.swift

Please add documentation on how to reuse a xib

**Comment by AndrewSB** [comment]
Hey @laurennicoleroth, there's an example in the [demo project](https://github.com/zhxnlai/ZLSwipeableViewSwift/blob/master/ZLSwipeableViewSwiftDemo/ZLSwipeableViewSwiftDemo/ZLSwipeableViewController.swift#L58) :smile:
