### ISSUE TITLE
Can't support Masonry?

### ISSUE THREAD

**Issue by GitterYang** [zhxnlai/ZLSwipeableViewSwift#61]
When I use masonry to layout the content UI, the first card show prefect. Then I drag this first card, The content UI was messy. At the same time, I set frame to layout the content UI, it runs prefect. Did it not support Masonry?

**Comment by AndrewSB** [comment]
Hey @CoderEic, it's an issue with AutoLayout, not masonry specifically. Check out https://github.com/zhxnlai/ZLSwipeableView/issues/9 😄

**Comment by GitterYang** [comment]
I have solve this problem, Thank you.
My solution: I put containerView use frame to layout, then other subviews use masonry to layout on containView, it works well.
