### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by jterrazz** [zhxnlai/ZLSwipeableViewSwift#63]
Hi guys, any date when u'll support swift 3 ?
Nice work by the way

**Comment by AndrewSB** [comment]
Not solid date yet, we'd be open to a PR with Swift 3 support though!

**Comment by Byoud01** [comment]
Any update on swift 3 or is the branch okay to use?

**Comment by AndrewSB** [comment]
Yup! I haven't tested it, but I believe our `swift3` branch is what you're looking for! It was merged in last week https://github.com/zhxnlai/ZLSwipeableViewSwift/pull/75
