### ISSUE TITLE
View subviews nil during swiping callback

### ISSUE THREAD

**Issue by mohonish** [zhxnlai/ZLSwipeableViewSwift#65]
Hi,

Firstly thanks for the wonderful library.

I implemented the SwipeableView to replicate the tinder-like cards loading from xib. I want to implement the feature where on swiping left a label appears on top right of the card view that says something like "swiping left".

To do this I created the view and added the "swiping left" label in xib with alpha zero. I'm trying to change alpha property of the subview of CardView during the swipe callback.

```
swipeableView.swiping = { view, location, translation in
    let thisView = view as! CardView
    let transPercentage = translation.x / 200
    thisView.joinView.alpha = abs(transPercentage)
}
```

The above code crashes at the line where I try to set the alpha property with error `fatal error: unexpectedly found nil while unwrapping an Optional value`. On inspecting I find that `thisView.joinView` is nil.

On the contrary, If i set `thisView.alpha = ...` it works fine as thisView is found to be the correct instance of CardView.

It seems that all the subviews of thisView are nil which is unexpected as the view has already been initialized and is visible.

How can I get a non-nil reference to my custom view subviews so that I can change their properties during swipe callback?

Thanks!

**Comment by mohonish** [comment]
Hi! Apologies. I can in fact get a correct reference to the view. I was actually passing `CardView` as a subview to a `UIView` in `nextView` which is why the crash was happening. My intended functionality works perfectly.

**Comment by AndrewSB** [comment]
👌
