### ISSUE TITLE
Adding swiped view back to the stack of views

### ISSUE THREAD

**Issue by Daemon-Devarshi** [zhxnlai/ZLSwipeableViewSwift#66]
I want to achieve something like this:
1. User swipes the top most view, either towards left or right
2. The swiped view is added to the bottom of view stack
3. So say if there were three views then first view is re-visible after third swipe

Is it something which can be achieved out of the box or does it need customization in existing code base? Any code pointers shall be helpful.

Thanks in advance.

**Comment by AndrewSB** [comment]
@Daemon-Devarshi take a look at the [`rewind()` function](https://github.com/zhxnlai/ZLSwipeableViewSwift/blob/master/ZLSwipeableViewSwift/ZLSwipeableView.swift#L140), I think if you copied a majority of the function, and change where the last swiped view is placed (the bottom of the stack, not the top), you'll reach the desired functionality.

**Comment by Daemon-Devarshi** [comment]
Thank you, I will definitely try it.
