### ISSUE TITLE
Changing CardView frame Size, causes next card to load in from bottom right corner

### ISSUE THREAD

**Issue by mparrish91** [zhxnlai/ZLSwipeableViewSwift#69]
![screen shot 2016-08-10 at 10 13 59 am](https://cloud.githubusercontent.com/assets/5642923/17563383/0476348a-5ee4-11e6-937a-a4231884c307.png)

![screen shot 2016-08-10 at 10 19 09 am](https://cloud.githubusercontent.com/assets/5642923/17563392/0b7a69b8-5ee4-11e6-9d60-625beb3485ca.png)

I changed the frame of the card view in the demo application and in my application.  Once that happens the card view loading is shown and comes in from the side.  How can I remove this to achieve the regular functionality?

**Comment by AndrewSB** [comment]
I've run into this before too, it's related to bounds vs. frame - really confusing. Here's a resource that helped me make some sense of it: http://stackoverflow.com/questions/1210047/cocoa-whats-the-difference-between-the-frame-and-the-bounds

Let me know if that fixes it 😄

**Comment by mparrish91** [comment]
I ended it up not needing to shrink it for now.  Thanks for the tip though!
