### ISSUE TITLE
Getting started with adding cards

### ISSUE THREAD

**Issue by madman3** [zhxnlai/ZLSwipeableViewSwift#70]
I'm only just getting started and couldn't get the cards to load on my main storyboard. I just think being a beginner, I'm having a difficulty getting off the ground. It was also interesting for me to learn that other pods like cartography also had to be installed to get the started. I assume it's probably a no brainer for seasoned programmers. But, I think as an amateur, it probably would be helpful to include in the getting started guideline to mention the pods that would be prerequisites. 

Here's how my main viewcontroller looks like. I couldn't quite figure out how to get this working. I'm using this class as a reference to my main storyboard - https://gist.github.com/madman3/67ba7715f7a70854a1d03036bcc8feb3

Are there anymore details that would be required to help?

**Comment by AndrewSB** [comment]
Hey @madman3! Awesome to see that you're using this library.

I'd recommend first checking out the demo projects [here](https://github.com/zhxnlai/ZLSwipeableViewSwift/tree/master/ZLSwipeableViewSwiftDemo), if you're still having trouble getting started after you've taken a look there, come back with what isn't working and I'd be happy to help 😄
