### ISSUE TITLE
Unable to add single card to view

### ISSUE THREAD

**Issue by mparrish91** [zhxnlai/ZLSwipeableViewSwift#72]
This might be a small/ dumb error.  I'm having difficulty adding a single card view to my swappable view.

Here is an image from the debugger. I've made sure everything is added properly in next card view and the debugger shows my view with the label text set properly.  Everything however is blank.

![screen shot 2016-08-27 at 1 19 19 am](https://cloud.githubusercontent.com/assets/5642923/18026220/8af8fb4c-6bf4-11e6-8529-8bfcad58e646.png)

**Comment by AndrewSB** [comment]
Can you also share the code where you're adding the view in code?
