### ISSUE TITLE
Swift 3 support ?

### ISSUE THREAD

**Issue by TheSwifter** [zhxnlai/ZLSwipeableViewSwift#77]
I wondering if you will upgrade ZLSSwipeableViewSwift to Swif 3.0

**Comment by AndrewSB** [comment]
yup! We have a `swift3` branch, it's ready to use 😄

**Comment by Byoud01** [comment]
Is it possible to have the demo app updated to swift 3 too?

**Comment by AndrewSB** [comment]
Yeah! Do you want to start a pull request? I can help review it there

**Comment by RebeccaB89** [comment]
Hi, do you have example runnable on Xcode 8.0 please?

**Comment by katriciab** [comment]
Yes, an updated demo would be super helpful.
