### ISSUE TITLE
flip the taped card

### ISSUE THREAD

**Issue by miladyalda** [zhxnlai/ZLSwipeableViewSwift#79]
does anyone know how to flip cards when user tap on it? I try to add

like this: [https://www.youtube.com/watch?v=AIgwab1o1c4(url)

`UIView.transition(from: self.nextCardView()!, to: self.backCardView()!, duration: 1, options: UIViewAnimationOptions.transitionFlipFromRight, completion: nil)`

nextCardView() and backCardView() return UIView.

```
func nextCardView() -> UIView? {
        if colorIndex >= colors.count {
            colorIndex = 0
        }

        print("nextCardView")
        let cardView = CardView(frame: swipeableView.bounds)

        //colorIndex

        //random funktion
        let random = Int(arc4random_uniform(20))
        cardView.backgroundColor = colorForName(colors[random])




        return cardView
    }

```

to swipeableView.didTap but it does not work anyone have any idea?

**Comment by hrishikeshnewage** [comment]
I made it like this - 

```
 if rearView.hidden {
   UIView.transitionWithView(mainView, duration: 0.5, options: .TransitionFlipFromLeft, animations: {
                self.rearView.hidden = false
    self.mainView.bringSubviewToFront(self.rearView)
                }, completion: {finished in
                    self.rearView.hidden = false
            })
       }
        else {
   UIView.transitionWithView(mainView, duration: 0.5, options: .TransitionFlipFromRight, animations: {
   self.mainView.bringSubviewToFront(self.frontView)
                }, completion: {finished in
                    self.rearView.hidden = true
            })

        }
```

where mainview is a view in the card view comprising of frontview and rear view
Intially put rearview as hidden and put frontview at the top 
on tapping the card, pass the correct index number of the card to a function inside CardView.swift and put the above code there.

**Comment by miladyalda** [comment]
thanks for the reply, you can please post the entire code of ud have it?

**Comment by roymckenzie** [comment]
Hey @hrishikeshnewage I noticed something strange when I implemented something similar to your code (and when I implemented your code to test why mine wasn't working). This works really well at flipping all the cards except for the last three cards in the stack. When one of the last three cards are flipped, the view doesn't get swapped out until you nudge the card a little bit after the flip.

Was wondering if you noticed that and if you had a solution if you had noticed it.

Thanks!

**EDIT:**

It is worth noting that when I remove the `transitionFlipFromLeft` (`transitionFlipFromRight`) animation option the correct side will show when tapped:

```
    UIView.transition(from: fromView,
                      to: toView,
                      duration: 0.6,
                      options: [.showHideTransitionViews]) { _ in
                            
        self.currentSide = self.currentSide.nextSide
    }
```

**Comment by roymckenzie** [comment]
Just wanted to let anyone know who might have had the same issue I had regarding rotating a card with this transition that if you have rasterization set to on for the layer of the view you are transitioning, you should turn off rasterization on the layer before doing the transition animation and then turn it back on when it's completed. Racked my brain for hours, but that was the issue.

**Comment by AndrewSB** [comment]
Awesome! It's awesome to see the community helping each other out. This looks solved, so I'll close it for now, but please don't hesitate to re-poen if something related comes up!
