### ISSUE TITLE
Version and tag in .podspec file should be updated

### ISSUE THREAD

**Issue by jonauz** [zhxnlai/ZLSwipeableViewSwift#80]
Because of **.podspec** not being updated, some fixes are not being pulled into the project on `pod install`.

`s.source       = { :git => "https://github.com/zhxnlai/ZLSwipeableViewSwift.git", :tag => "0.0.7" }`

Which doesn't make any sense. If major change was done (like Swift 3) or at least some fixes, which were merged to master, then this "tag" and even "version" should be updated.

Am I wrong?
At least I discovered this, when noticed that our pods local files do not include latest fix. But Podfile was configured to fetch latest code.

For now I forked and removed old version tag, and now `pod install` fetches latest commits as it should.

**Comment by AndrewSB** [comment]
@jonauz you're completely correct. Would you make a pull request from your branch into this one?

I'd be happy to merge your updates in 👍

**Comment by GlisboaDev** [comment]
@AndrewSB I changed the file and created a PR, could you merge it in? Thanks!

**Comment by AndrewSB** [comment]
Thanks @GlisboaDev!
