### ISSUE TITLE
Unable to edit the outlet objects in the xib

### ISSUE THREAD

**Issue by hrishikeshnewage** [zhxnlai/ZLSwipeableViewSwift#81]
If i put an imageview with a label, i can see them when the app runs.
But, when i look to change the text value of the label or when i look to change the image of the imageview, through code, its not changing..its instead showing the original values which i put in the xib.
I put the outlets in cardcontentview.xib and made objects in cardview.swift and Iam looking to change its value in nextCardView().
I dont know if its an issue or a problem in my side. Please clarify.

**Comment by AndrewSB** [comment]
Hey @hrishikeshnewage! It sounds like an issue setting with setting up your `IBOutlets`. I'd recommend debugging to make sure that your outlet is actually connected.

Sorry I can't be of more help! There are so many possible reasons you could be facing your issue.
Do let us know if you're able to fix it 😀

**Comment by AndrewSB** [comment]
@hrishikeshnewage: I'm closing this for now, but do come back if you're still facing this problem!
