### ISSUE TITLE
UIScrollView in card

### ISSUE THREAD

**Issue by ghysrc** [zhxnlai/ZLSwipeableViewSwift#87]
I have some cards only allow to swipe up or down. And I have a scrollview in every card to show some images, it allows horizontal scroll. 
Here is the problem, when I attempt to scroll the images, the card moves a little and nothing happen to the scrollview.
So, what can I do to make the scrollview works ?

**Comment by AndrewSB** [comment]
take a look at the UIGestureRecognizer delegate method [gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)](https://developer.apple.com/reference/uikit/uigesturerecognizerdelegate/1624208-gesturerecognizer)

If you implement it, you'll be able to recognize the swipe on the card & the scrollView simultaneously, or selectively disable one of the gesture recognizers

**Comment by ghysrc** [comment]
@AndrewSB Thanks for responding. I will try it.
