### ISSUE TITLE
Dismiss/discard a card without invoking swipe action

### ISSUE THREAD

**Issue by JoeFerrucci** [zhxnlai/ZLSwipeableViewSwift#90]
Need to just discard the top card without actually triggering/invoking a swiping action. 

Don't wan't to swipe any direction, just need to programmatically dismiss/discard the top card. 

Example: if there are three (3) cards, typically I would swipe in a direction and the respective action would be invoked. There's an action for each direction (Up, Down, Left, Right); so we typically have 4 actions. 

However, I need a fifth (5th) action, which is just get rid of the top card. I would get rid of the top card, which would mean there are only 2 cards, so I'd need a new one to be pushed on the bottom of the cards. 

Diagram of card view stack before and after this "discard-action" that I need:
`[1] [2] [3]` **->** `"DISCARD-ACTION"` **->** `[2] [3] [4]`

Hopefully I'm making sense.

Is there something comparable to what I need, `i.e., ZLSwipeableView.discardTopView()`

**Comment by AndrewSB** [comment]
@JoeFerrucci `discardTopView()` sure sounds useful. I think it should be something along the lines of calling `discardAllViews`, manually setting your index to +1 what it previously was, and then calling `loadViews` again.

After you've got it working, it would be awesome for you to share your code, we could make a function `discardTopView()` for people who want to do this in the future 😄

**Comment by AndrewSB** [comment]
Implementing in #103
