### ISSUE TITLE
Swift 3 release not pushed to CocoaPods

### ISSUE THREAD

**Issue by DenTelezhkin** [zhxnlai/ZLSwipeableViewSwift#91]
Hey!

It seems like podspec was updated in master to 0.0.8 version, but this version was never pushed to CocoaPods trunk. 

It would be great if you pushed it.

**Comment by 4np** [comment]
Temporary workaround

```
pod 'ZLSwipeableViewSwift', :git => 'https://github.com/zhxnlai/ZLSwipeableViewSwift.git', :commit => '60a900b'
```

**Comment by AndrewSB** [comment]
@DenHeadless I'm not very familiar with cocoapods, but if you create a Pull Request that updates trunk, I'd happily merge it!

**Comment by DenTelezhkin** [comment]
@AndrewSB There's no way to push to CocoaPods using Pull Request, only author can do it in command line

https://guides.cocoapods.org/making/getting-setup-with-trunk.html

You need to be registered author and call 

```
pod trunk push 
```

in directory with your podspec file.

**Comment by AndrewSB** [comment]
@zhxnlai I think you're going to have to do this

**Comment by samjarman** [comment]
Bump - any progress on this? :)

**Comment by AndrewSB** [comment]
@zhxnlai

**Comment by coolcool1994** [comment]
I CANNOT USE COCOAPOD  for this library!!!! PlZ UPDATE!

**Comment by AndrewSB** [comment]
@coolcool1994 there's a temp workaround, mentioned by @4np 

```
pod 'ZLSwipeableViewSwift', :git => 'https://github.com/zhxnlai/ZLSwipeableViewSwift.git', :commit => '60a900b'
```

**Comment by zackshapiro** [comment]
Any updates on this?
