### ISSUE TITLE
How to stop the repeatative swiping view?

### ISSUE THREAD

**Issue by Ashmika** [zhxnlai/ZLSwipeableViewSwift#92]
Hello,

 As I have use this demo it will work good,But Just minor problem is that When I swipe the card it will again added to view and show the repeated card Again n Again. SO can anyone tell how to stop that repeating and don't want to show again Repeat data.

Thanks in Advance..Appreciate for help....

**Comment by AndrewSB** [comment]
@Ashmika to see why your implementation is repeating data we'd need to take a look at your code

**Comment by Ashmika** [comment]
I use this demo only and run it ,it will add the card again in the repetitive mode so i didn't get any link about that to stop adding cards again.

**Comment by sagariosdev** [comment]
@Ashmika  In terms of stop new view loaded after swiping a view.
You must have to decrease number of active view *numberOfActiveView*
 and at the last called *swipeableView.discardViews()*

**Comment by Ashmika** [comment]
@jigneshiosdev  where i have to decrease the `numberOfActiveView` can u tell me any method in this code.

**Comment by sagariosdev** [comment]
@Ashmika 
You can decrease *numberOfActiveView* in this closer
  `swipeableView.didSwipe = {view, direction, vector in
    print("Did swipe view in direction: \(direction), vector: \(vector)")
}`

**Comment by Ashmika** [comment]
No its not working.I want to stop the repeat adding cards.

**Comment by sagariosdev** [comment]
Have you decrement *numberOfActiveView* every swipe in * didSwipe* closer Like

```
swipeableView.didSwipe = {view, direction, vector in 

swipeableView.numberOfActiveView = swipeableView.numberOfActiveView -1

if (swipeableView.numberOfActiveView == 0)
{
 swipeableView.discardViews()
}
}
```


OR you can decrement *numberOfActiveView* in `nextCardView()` method too.

**Comment by Ashmika** [comment]
@jigneshiosdev  Thank you so much its work..I decrement the `numberOfActiveView` in wrong method...Its really Work...Thank you...
