### ISSUE TITLE
Rewind not working if you have 1 active view

### ISSUE THREAD

**Issue by Marini83** [zhxnlai/ZLSwipeableViewSwift#94]
Rewind does work in that it keeps track  of those cards that need to be put back, however it skips the same number of cards on the main index . For instance, say you rewind 5 times, you can put those 5 cards, back but the index will move forward by 5 indexes as well so you will skip 5 cards too.

**Comment by Marini83** [comment]
I was able to update the index

**Comment by AndrewSB** [comment]
Happy to see you were able to figure it out!
