### ISSUE TITLE
How to make card same like tinder?

### ISSUE THREAD

**Issue by sagariosdev** [zhxnlai/ZLSwipeableViewSwift#97]
How we can make card swipe like tinder without rotating and scale.

**Comment by sagariosdev** [comment]
I had changed the code like this way
but still it rotating..

    fileprivate func attachView(toPoint point: CGPoint) {
        anchorView.center = point
        anchorView.backgroundColor = UIColor.blue
        anchorView.isHidden = true
        
        // attach aView to anchorView
        let p = view.center
        let offset = UIOffsetMake((point.x - view.bounds.midX) ,( point.y - view.bounds.midY))
        viewToAnchorViewAttachmentBehavior = UIAttachmentBehavior(item: view, offsetFromCenter: offset, attachedTo: anchorView, offsetFromCenter: offset)
        viewToAnchorViewAttachmentBehavior!.length = 0
        
        // attach anchorView to point
        anchorViewToPointAttachmentBehavior = UIAttachmentBehavior(item: anchorView, offsetFromCenter: offset, attachedToAnchor: point)
        anchorViewToPointAttachmentBehavior!.damping = 100
        anchorViewToPointAttachmentBehavior!.length = 0
        
        addBehavior(viewToAnchorViewAttachmentBehavior!)
        addBehavior(anchorViewToPointAttachmentBehavior!)
    }

**Comment by sagariosdev** [comment]
Ok thanks,
I got a solution so no more need to help.
Thanks again...

**Comment by chlebta** [comment]
@sagariosdev could you share the code ?

**Comment by sagariosdev** [comment]
@chlebta  here is code
Thanks.

fileprivate func attachView(toPoint point: CGPoint) {
        anchorView.center = view.center
        anchorView.backgroundColor = UIColor.blue
        anchorView.isHidden = true
        
        
        let offset = UIOffsetMake((point.x - view.bounds.midX) ,( point.y - view.bounds.midY))
        viewToAnchorViewAttachmentBehavior = UIAttachmentBehavior(item: view, offsetFromCenter: UIOffset.zero, attachedTo: anchorView, offsetFromCenter: UIOffset.zero)
        viewToAnchorViewAttachmentBehavior!.length = 0
        
        // attach anchorView to point
        anchorViewToPointAttachmentBehavior = UIAttachmentBehavior(item: anchorView, offsetFromCenter: offset, attachedToAnchor: point)
        anchorViewToPointAttachmentBehavior!.damping = 100
        anchorViewToPointAttachmentBehavior!.length = 0
        
        addBehavior(viewToAnchorViewAttachmentBehavior!)
        addBehavior(anchorViewToPointAttachmentBehavior!)
    }

**Comment by chlebta** [comment]
@sagariosdev  thank's you saved my morning ;)

But sorry where to put it ?
